/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: "#10b981", 
        "primary-container": "#d1fae5",
        "primary-dim": "#059669",
        "primary-fixed": "#10b981",
        "primary-fixed-dim": "#059669",
        "on-primary": "#ffffff",
        "on-primary-container": "#064e3b",
        "on-primary-fixed": "#022c22",
        "on-primary-fixed-variant": "#064e3b",
        secondary: "#34d399",
        "secondary-container": "#ecfdf5",
        "secondary-dim": "#10b981",
        "secondary-fixed": "#34d399",
        "secondary-fixed-dim": "#10b981",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#064e3b",
        "on-secondary-fixed": "#022c22",
        "on-secondary-fixed-variant": "#064e3b",
        tertiary: "#64748b",
        "tertiary-container": "#f1f5f9",
        "tertiary-dim": "#475569",
        "tertiary-fixed": "#cbd5e1",
        "tertiary-fixed-dim": "#94a3b8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#0f172a",
        "on-tertiary-fixed": "#020617",
        "on-tertiary-fixed-variant": "#1e293b",
        background: "#ffffff",
        "on-background": "#0f172a",
        surface: "#ffffff",
        "surface-bright": "#f8fafc",
        "surface-dim": "#f1f5f9",
        "surface-variant": "#e2e8f0",
        "surface-container": "#f8fafc",
        "surface-container-low": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#64748b",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f1f5f9",
        "inverse-primary": "#a7f3d0",
        error: "#ef4444",
        "error-container": "#fef2f2",
        "error-dim": "#dc2626",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d",
        outline: "#cbd5e1",
        "outline-variant": "#e2e8f0",
        "surface-tint": "#10b981",
      },
      fontFamily: {
        "space-grotesk": ["Space Grotesk", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        'soft': '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
        'glow': '0 0 20px rgba(16, 185, 129, 0.4)',
      }
    },
  },
  plugins: [],
}
