const sample1 = {
  match_score: 92,
  technical_questions: [
    '<question>You have two unsorted arrays of integers, `arr1` and `arr2`. Write a function that returns a new array containing only the elements that are common to both `arr1` and `arr2`, without duplicates. Discuss the time and space complexity of your solution.</question>',
    "<intention>This question aims to evaluate the candidate's understanding of Data Structures and Algorithms, specifically array manipulation, hash maps/sets, and efficiency analysis (time/space complexity). It assesses their problem-solving approach and ability to choose appropriate data structures for optimal performance.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Identify edge cases (empty arrays). Discuss different approaches: brute-force (nested loops), sorting and two-pointers, or using a hash set. Explain the trade-offs in terms of time and space complexity for each approach. The optimal solution will likely involve a hash set for efficient lookups.</points_to_cover>',
    '<approach>Start by explaining a naive approach (e.g., nested loops) and its complexity (O(N*M)). Then, propose an optimized solution using a hash set: add all elements from the first array to a hash set, then iterate through the second array, checking if each element exists in the hash set. If it does, add it to the result array and ensure no duplicates are added to the final result. Clearly state the improved time complexity (O(N+M)) and space complexity (O(N) or O(M)).</approach>',
    '</how_to_answer>',
    '<question>You are building a REST API for a simple e-commerce product catalog. Design the API endpoints for managing products, including operations to: 1. Create a new product. 2. Retrieve a specific product by ID. 3. Update an existing product. 4. Delete a product. 5. List all products with optional filtering by category. For each endpoint, specify the HTTP method, the URL path, and a brief example of the request/response body.</question>',
    "<intention>This question assesses the candidate's understanding of RESTful API design principles, HTTP methods, status codes, and practical application of Node.js/Express.js concepts. It also evaluates their ability to design clear and functional API interfaces.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Clearly define resource naming (e.g., `/products`). Map standard CRUD operations to appropriate HTTP methods (POST, GET, PUT/PATCH, DELETE). Show how to handle specific resources (e.g., `/products/:id`). Demonstrate how filtering/query parameters work for listing resources. Provide example JSON request and response bodies, including appropriate HTTP status codes (200, 201, 204, 400, 404).</points_to_cover>',
    '<approach>For each operation, specify: HTTP Method (e.g., `POST`), Path (e.g., `/api/products`), and then provide a sample JSON request body (for POST/PUT) and a sample JSON response body (for GET/POST/PUT). For listing all products, explain how query parameters like `/api/products?category=electronics` would work. Mention error handling briefly (e.g., returning 404 for not found).</approach>',
    '</how_to_answer>',
    "<question>In your 'Raksha' project, you used Appwrite for backend services. Can you explain how Appwrite abstracts common backend functionalities and what specific advantages or disadvantages you found compared to building a backend from scratch with Node.js/Express.js and MongoDB?</question>",
    "<intention>This question aims to understand the candidate's experience with BaaS (Backend-as-a-Service) solutions like Appwrite, their awareness of architectural trade-offs, and their ability to compare different backend approaches. It also probes into their practical project experience and critical thinking.</intention>",
    '<how_to_answer>',
    "<points_to_cover>Explain Appwrite's core features (authentication, databases, storage, functions, real-time). Discuss how it simplifies development by providing ready-to-use APIs. Compare it with a custom Node.js/Express.js/MongoDB stack, focusing on aspects like development speed, flexibility, control, scalability, and vendor lock-in. Mention specific benefits or limitations encountered in the Raksha project.</points_to_cover>",
    '<approach>Start by describing what Appwrite provided for Raksha (e.g., user management, data storage). Then, list the advantages (faster development, less boilerplate, managed services, built-in features). Follow with disadvantages (less control over specific logic, potential performance limitations, learning curve for Appwrite-specific APIs, vendor lock-in). Conclude by summarizing when one approach might be preferred over the other.</approach>',
    '</how_to_answer>',
    '<question>You mentioned an interest in backend development and cloud technologies. From a backend perspective, how would you approach ensuring your Node.js application is robust and can handle increasing user traffic and data volume? What steps would you take to make it more scalable?</question>',
    "<intention>This question gauges the candidate's understanding of system design, scalability concepts, and best practices for building robust backend applications beyond basic CRUD operations. It explores their forward-thinking and awareness of production-level concerns.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Discuss horizontal scaling (load balancing, running multiple instances). Mention database optimization strategies (indexing, sharding, replication). Explain caching mechanisms (Redis, Memcached). Talk about asynchronous processing/message queues (RabbitMQ, Kafka) for long-running tasks. Discuss monitoring and logging. Briefly touch upon microservices or serverless architectures as advanced scaling patterns.</points_to_cover>',
    '<approach>Start by breaking down the problem into different layers: application layer, database layer, and infrastructure. For each layer, propose specific strategies. For example, for the application layer, suggest load balancing and containerization (Docker). For the database, mention optimizing queries and considering replication. Emphasize that scalability is an ongoing process and involves continuous monitoring and optimization.</approach>',
    '</how_to_answer>'
  ],
  behavioral_questions: [
    '<question>You mentioned participating in hackathons and enjoying working in teams. Can you describe a specific experience in a team project or hackathon where you faced a significant technical disagreement or conflict with a team member? How did you handle it, and what was the outcome?</question>',
    "<intention>This question aims to assess the candidate's teamwork, conflict resolution, communication, and collaboration skills, which are crucial for success in a professional software development environment.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Use the STAR method (Situation, Task, Action, Result). Clearly describe the disagreement (Situation). Explain your role and the task at hand (Task). Detail the specific actions you took to address the conflict (Action), focusing on active listening, presenting your perspective constructively, finding common ground, or compromising. Finally, describe the resolution and what you learned from the experience (Result).</points_to_cover>',
    '<approach>Choose an actual event. Focus on demonstrating maturity and a constructive approach. Emphasize problem-solving over blame. Show you can respect other viewpoints and work towards a shared goal. The outcome should ideally be positive or, if not, offer a clear lesson learned.</approach>',
    '</how_to_answer>',
    '<question>You mentioned solving 50+ problems on LeetCode and actively participating in coding contests. Tell me about a time you encountered a particularly difficult problem (either in competitive programming or a project) that you initially struggled to solve. Walk me through your thought process from encountering the problem to eventually finding a solution.</question>',
    "<intention>This question assesses the candidate's problem-solving methodology, persistence, debugging skills, and ability to learn and adapt when faced with complex technical challenges. It also probes into their self-motivation and intellectual curiosity.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Use the STAR method. Describe the problem clearly. Explain your initial understanding and any initial incorrect approaches. Detail the steps you took: breaking down the problem, researching (e.g., similar patterns, algorithms), debugging, testing different ideas. Highlight any resources used (documentation, peers, online forums). Conclude with the solution found and the key lessons learned about problem-solving or a specific concept.</points_to_cover>',     
    "<approach>Be specific about the technical details of the problem and your solutions. Show a structured approach to problem-solving. Emphasize resilience and the iterative nature of finding a solution. Don't be afraid to mention false starts or difficulties, as this demonstrates a realistic approach to complex problems.</approach>",
    '</how_to_answer>',
    '<question>In your self-description, you candidly mentioned that you sometimes struggle with confidence while speaking in front of people but are actively working on improving your communication skills. Could you elaborate on this? What specific steps are you taking to address this challenge, and what progress have you observed?</question>',
    "<intention>This question directly addresses a self-identified area for growth. It aims to assess the candidate's self-awareness, proactivity in personal development, willingness to acknowledge weaknesses, and commitment to improving essential soft skills.</intention>",
    '<how_to_answer>',
    "<points_to_cover>Acknowledge the challenge honestly. Provide specific examples of situations where this difficulty manifests. Detail concrete actions you are taking (e.g., practicing presentations, joining Toastmasters/public speaking groups, volunteering to speak in class, preparing talking points more thoroughly). Discuss any positive progress or improvements you've noticed, even small ones, and your future goals for improvement.</points_to_cover>",
    "<approach>Be open and specific. Focus on the 'actively working on' aspect. Demonstrate initiative and a growth mindset. This question is an opportunity to turn a perceived weakness into a strength by showing commitment to self-improvement. Avoid vague answers; provide actionable steps and observed outcomes.</approach>",
    '</how_to_answer>',
    "<question>You've gained experience in various areas, from full-stack development to competitive programming. What aspects of this Software Developer Intern role, specifically within backend or full-stack development, are you most excited about, and how do you see it aligning with your long-term career aspirations?</question>",
    "<intention>This question aims to understand the candidate's motivation, enthusiasm for the specific role, and how they envision their career path. It helps determine if their personal goals align with the opportunities offered by the internship.</intention>",
    '<how_to_answer>',
    '<points_to_cover>Express genuine enthusiasm for the role and the company. Highlight specific responsibilities or technologies mentioned in the job description that align with your skills and interests (e.g., Node.js, MongoDB, scalable web applications, collaboration). Connect this internship to your interest in backend development and cloud technologies. Discuss how this experience would help you grow professionally and contribute to your long-term career goals.</points_to_cover>',
    '<approach>Be specific and authentic. Research the company and role beforehand. Show how your current skills and future aspirations make you a good fit. Articulate what you hope to learn and how you plan to contribute, demonstrating a proactive and goal-oriented mindset.</approach>',
    '</how_to_answer>'
  ],
  skills_gaps: [
    '<skill>Explicit Cloud Platform Expertise (AWS/Azure/GCP)</skill>',
    '<severity>Medium</severity>',
    '<skill>Professional Communication & Presentation Confidence</skill>',
    '<severity>Medium</severity>',
    '<skill>Advanced Database Optimization & Management</skill>',
    '<severity>Low</severity>',
    '<skill>Unit/Integration Testing Practices</skill>',
    '<severity>Low</severity>'
  ],
  preparation_plan: [
    '<day>Day 1</day>',
    '<focused_topic>Data Structures & Algorithms</focused_topic>',
    '<tasks>Review fundamental data structures (arrays, linked lists, hash maps, trees, graphs). Practice common algorithms (sorting, searching, two-pointers, recursion, basic dynamic programming) on LeetCode. Focus on analyzing time and space complexity for all solutions. Prioritize problems related to arrays, strings, and hash tables.</tasks>',
    '<day>Day 2</day>',
    '<focused_topic>Backend Development (Node.js, Express.js, REST APIs)</focused_topic>',
    '<tasks>Review Node.js asynchronous programming concepts (callbacks, Promises, async/await). Practice building a simple CRUD REST API using Express.js and MongoDB. Understand HTTP methods, status codes, and proper API design principles (resource-based naming, handling query parameters). Be ready to explain how to secure APIs.</tasks>',
    '<day>Day 3</day>',
    '<focused_topic>Databases (MongoDB) & Project Deep Dive</focused_topic>',
    "<tasks>Review MongoDB CRUD operations, indexing, and basic aggregation queries. Understand different data modeling approaches (embedding vs. referencing) for MongoDB. Prepare to discuss 'Raksha' and 'Gym Website' projects in detail: architecture, technologies used, specific contributions, challenges faced, and how they were overcome. Be ready to explain technical decisions.</tasks>",
    '<day>Day 4</day>',
    '<focused_topic>Frontend (React.js) & Version Control (Git)</focused_topic>',
    '<tasks>Review React.js fundamentals (components, props, state, hooks, component lifecycle). Understand how frontend and backend interact (e.g., fetching data from REST APIs). Practice essential Git commands (add, commit, push, pull, branch, merge, rebase) and common Git workflows. Be able to explain concepts like pull requests and conflict resolution.</tasks>',
    '<day>Day 5</day>',
    '<focused_topic>Behavioral Questions & Cloud Basics & Communication Practice</focused_topic>',
    "<tasks>Prepare answers for common behavioral questions using the STAR method, focusing on teamwork, problem-solving, and learning experiences. Specifically prepare for questions about communication skills and how you are actively improving them. Research basic concepts of a popular cloud platform (e.g., AWS EC2, S3, Lambda or Azure equivalents) to cover the 'plus' requirement. Practice self-introduction and articulating 'why this role' confidently.</tasks>",
  ]
}

const sample2= 
{
  'Match Score': 88,
  'Technical Questions': [
    "Question: Explain the concept of 'hoisting' in JavaScript. How does it apply to 'var', 'let', and 'const'?",
    "Intention: To assess the candidate's fundamental understanding of JavaScript's execution context and variable declaration mechanisms.",
    "How to Answer: Clearly define hoisting and then differentiate its behavior for 'var' (declared and initialized with undefined), 'let'/'const' (hoisted but not initialized, resulting in Temporal Dead Zone errors).",
    "Points to Cover: Definition of hoisting, behavior of 'var' (function-scoped), 'let'/'const' (block-scoped), and the Temporal Dead Zone.",
    'Approach: Start with a general definition, then provide specific examples for each keyword to illustrate the differences.',
    "Question: You've used Node.js and Express.js. Describe the role of middleware in an Express.js application and provide a practical example of when you would use it.",
    "Intention: To evaluate the candidate's practical experience and understanding of Express.js architecture and how to extend its functionality.",
    'How to Answer: Define middleware, explain its sequential execution, and then give an example such as authentication, logging, or error handling.',
    "Points to Cover: What middleware is, how it intercepts requests/responses, the 'next()' function, and a clear use case.",
    'Approach: Define the concept, explain its flow, and then walk through a code example or a detailed scenario.',      
    "Question: In MongoDB, what are indexes, and why are they crucial for application performance? How would you decide which fields to index in your 'Raksha' project's database?",
    "Intention: To test the candidate's knowledge of database optimization techniques and practical application in a NoSQL context.",
    "How to Answer: Explain what an index is, how it speeds up queries, and provide a thoughtful justification for indexing specific fields in the 'Raksha' project.",
    'Points to Cover: Definition of an index, B-tree structure (optional but good), performance benefits (query speed), and considerations for indexing (e.g., frequently queried fields, unique fields).',
    'Approach: Define the concept, explain its benefits with analogy if helpful, and then apply it directly to a project scenario with rationale.',
    "Question: Describe the architecture of your 'Raksha' (Disaster Management System) project. How do different components (frontend, backend, Appwrite) communicate with each other?",
    "Intention: To understand the candidate's ability to think about system design at a high level and articulate technical flows within a project they built.",
    "How to Answer: Outline the main components, their individual roles, and specifically detail how data flows and communication happens between them, including Appwrite's role.",
    "Points to Cover: Frontend (React), Backend (Node.js/Appwrite), Database (Appwrite's built-in DB), APIs, user authentication flow, emergency alert system flow.",
    'Approach: Start with a high-level overview, then drill down into specific communication protocols and data exchange methods.',
    "Question: You mentioned building REST APIs. What are the key principles of a RESTful API, and how would you design an API endpoint for fetching a list of active emergency alerts in your 'Raksha' system?",
    'Intention: To assess understanding of REST architectural style and practical API design skills.',
    'How to Answer: List and briefly explain REST principles (stateless, client-server, cacheable, uniform interface, etc.) and then propose a specific API endpoint with HTTP method, URI, and potential query parameters.',
    'Points to Cover: Resource-based URLs, HTTP methods (GET, POST, PUT, DELETE), statelessness, status codes. For the example: Method (GET), URI (/api/alerts?status=active), expected response.',
    'Approach: Define the principles first, then demonstrate their application by designing a concrete API endpoint.',   
    'Question: How do you handle asynchronous operations in Node.js? Can you explain the difference between callbacks, Promises, and async/await?',
    "Intention: To gauge understanding of JavaScript's asynchronous nature, critical for Node.js development, and evolution of handling async code.",
    'How to Answer: Explain why async operations are needed. Describe each method (callbacks, Promises, async/await) in terms of syntax, common use cases, and how they improve readability/manageability.',
    'Points to Cover: Event Loop (briefly), Callback Hell, Promise chaining (.then(), .catch()), async/await syntax, error handling in each method.',
    'Approach: Start with the problem of async code, then present each solution chronologically, highlighting advantages of newer methods.',
    "Question: You've solved 50+ LeetCode problems. Describe a data structure that you find particularly useful for solving a specific type of problem, and provide an example.",
    'Intention: To go beyond mere problem-solving count and assess deeper understanding of data structure applications and their performance implications.',
    'How to Answer: Choose a data structure (e.g., Hash Map, Stack, Queue, Tree), explain its properties, and illustrate with a common algorithm or LeetCode-style problem.',
    'Points to Cover: Data structure name, its characteristics, time/space complexity of operations, and a specific problem where it excels.',
    'Approach: Select a data structure, define it, explain its pros/cons for a certain problem type, and give a clear problem example.',
    'Question: When collaborating on projects using Git, you encounter a merge conflict. Describe the steps you would take to resolve it.',
    'Intention: To test practical Git workflow knowledge, especially in a team environment.',
    'How to Answer: Explain what a merge conflict is and then detail the precise Git commands and manual steps to identify, resolve, and commit the changes.',
    'Points to Cover: Identifying conflict markers, using `git status`, opening the conflicted file, manual editing, `git add`, `git commit`.',
    'Approach: Simulate the scenario, list the commands, and describe the manual intervention required.',
    'Question: How do you ensure the code you write is clean, readable, and maintainable, especially when working on a team project?',
    'Intention: To assess awareness of code quality standards and best practices beyond just functionality.',
    'How to Answer: Discuss specific practices you follow, such as naming conventions, modularity, comments (judiciously), linting, and testing.',
    'Points to Cover: Meaningful variable/function names, small functions, clear comments, consistent formatting, modular design, adherence to style guides, self-documenting code.',
    'Approach: State the importance of clean code, then list specific actionable strategies and examples from your experience.',
    'Question: You mentioned basic knowledge of cloud platforms is a plus for this role. What aspects of cloud computing are you most interested in, and why?',
    "Intention: To explore the candidate's genuine interest in cloud technologies and assess their potential for learning in that area.",
    'How to Answer: Express specific interests (e.g., serverless, containerization, scalable databases, specific cloud providers) and explain the reasoning behind that interest.',
    'Points to Cover: Specific cloud services or concepts, potential benefits (scalability, cost-efficiency), how it relates to backend development, and future learning goals.',
    'Approach: Be specific about areas of interest, show enthusiasm, and connect it to the job role or future career aspirations.'
  ],
  'Behavioral Questions': [
    'Question: Tell me about a time you had to learn a new technology or framework quickly for a project. How did you approach it, and what was the outcome?',
    "Intention: To assess the candidate's learning agility, resourcefulness, and ability to adapt to new tools and environments.",
    'How to Answer: Use the STAR method. Describe the Situation where you needed to learn something new, the Task you had to accomplish, the Actions you took (e.g., online tutorials, documentation, experimentation), and the Result (successful project, new skill acquired).',
    'Points to Cover: Specific technology, the challenge, steps taken to learn, difficulties encountered, and positive outcome.',
    'Approach: Clearly structure your answer using STAR (Situation, Task, Action, Result) to provide a comprehensive response.',
    'Question: Describe a challenging technical problem or bug you encountered in one of your projects (e.g., Raksha, Gym Website). How did you approach debugging and ultimately resolve it?',
    'Intention: To evaluate problem-solving skills, persistence, debugging methodologies, and ability to learn from mistakes.',
    'How to Answer: Use the STAR method. Detail the specific bug, its impact (Situation), what needed to be fixed (Task), the troubleshooting steps you took (Actions), and how it was resolved (Result).',
    'Points to Cover: Nature of the bug, initial assumptions, debugging tools used, collaboration (if any), steps taken to isolate the problem, and the final solution.',
    'Approach: Walk through the problem-solving process logically, highlighting your analytical thinking and resilience.',
    "Question: You've participated in hackathons and taken leadership roles. Tell me about a time you worked effectively in a team under pressure to meet a deadline.",
    'Intention: To gauge teamwork, collaboration, time management, and performance under high-pressure situations.',     
    "How to Answer: Use the STAR method. Describe the hackathon or project setting, the tight deadline (Situation), your team's goal (Task), your specific contributions and how you collaborated (Actions), and the final outcome (Result).",    
    'Points to Cover: Team dynamics, division of labor, communication strategies, conflict resolution (if any), and successful delivery.',
    'Approach: Emphasize your role as a team player, your ability to contribute under pressure, and the positive team outcome.',
    'Question: You mentioned sometimes struggling with confidence while speaking. Can you describe a situation where you found it challenging to communicate a technical idea, and what you learned from it?',
    "Intention: To assess self-awareness, growth mindset, and proactive efforts in improving communication skills, a key 'preferred' skill.",
    "How to Answer: Use the STAR method. Identify a specific instance (Situation), explain what you needed to communicate (Task), detail your approach and the difficulties faced (Actions), and critically reflect on what you learned and how you've improved (Result).",
    "Points to Cover: Specific communication challenge, impact of the challenge, strategies you're using to improve (e.g., practice, structured explanations), and observable progress.",
    'Approach: Be honest about the challenge, but focus heavily on your efforts towards improvement and the lessons learned.',
    'Question: How do you prioritize tasks when you have multiple responsibilities or project deadlines? Can you give an example from your academic or project experience?',
    "Intention: To understand the candidate's organizational skills, ability to manage workload, and decision-making under competing demands.",
    'How to Answer: Use the STAR method. Describe a scenario with competing tasks (Situation), what needed to be done (Task), your prioritization method (Actions), and how you managed to meet commitments (Result).',
    'Points to Cover: Prioritization techniques (e.g., urgency vs. importance, impact analysis), flexibility, communication with stakeholders, and successful outcome.',
    'Approach: Clearly articulate your prioritization strategy and back it up with a concrete example.',
    'Question: What interests you most about backend development, and what specific areas or technologies within backend development do you hope to explore or specialize in during this internship?',
    "Intention: To assess genuine interest, motivation, and alignment with the role's focus on backend/full-stack.",     
    "How to Answer: Express your passion for backend, citing specific aspects (e.g., scalability, data management, API design, performance). Mention specific technologies or concepts you're eager to learn, connecting them to the job description.",
    'Points to Cover: Reasons for backend preference, connection to problem-solving, specific Node.js/Express/MongoDB features of interest, and interest in cloud platforms.',
    "Approach: Be enthusiastic, specific, and show how your interests align with the company's work and the internship's learning opportunities.",
    'Question: Tell me about a time you received constructive criticism or feedback on your code or work. How did you react, and what did you do with that feedback?',
    'Intention: To evaluate coachability, openness to feedback, and ability to improve based on input.',
    'How to Answer: Use the STAR method. Describe the context of the feedback (Situation), what the feedback was about (Task), how you processed it and acted upon it (Actions), and the positive impact of your changes (Result).',
    'Points to Cover: Source of feedback, specific nature of the criticism, your initial reaction, steps taken to implement the feedback, and improved outcome.',
    'Approach: Show humility, a willingness to learn, and demonstrate how you translate feedback into positive action.', 
    'Question: How do you ensure the quality of your work, especially when working on a project that might have a significant impact (like the Raksha system)?',
    "Intention: To understand the candidate's commitment to quality, attention to detail, and awareness of the impact of their work.",
    'How to Answer: Discuss your approach to writing clean, well-tested, and robust code. Mention code reviews, self-testing, and considering edge cases.',
    'Points to Cover: Thorough testing (manual/automated if applicable), understanding requirements, error handling, input validation, code reviews (even self-reviews), and thinking about potential failures.',
    'Approach: Provide concrete examples of how you integrate quality checks throughout your development process.',      
    "Question: You listed experience as a 'Software Specialist' and 'Technical Coordinator'. Can you describe a time when you took initiative to solve a problem or improve a process, even if it wasn't explicitly your responsibility?",        
    'Intention: To assess proactiveness, initiative, and leadership potential, even in an intern role.',
    'How to Answer: Use the STAR method. Describe the situation where you identified an opportunity for improvement (Situation), what you saw needed to be done (Task), the steps you took on your own initiative (Actions), and the positive outcome (Result).',
    'Points to Cover: Identifying the problem, taking ownership, planning, execution, and the benefits achieved.',       
    'Approach: Highlight your ability to identify needs and proactively contribute beyond your defined role.',
    'Question: Where do you see yourself in terms of skill development in the next year, particularly concerning backend and cloud technologies, and how does this internship align with those goals?',
    "Intention: To understand the candidate's career aspirations, self-motivation, and how well they've researched and aligned their goals with the company and role.",
    "How to Answer: Articulate specific, realistic skill development goals related to backend (e.g., deeper understanding of Node.js performance, microservices, specific cloud services like serverless functions or container orchestration) and explain how the internship's responsibilities and learning opportunities will help you achieve them.",
    "Points to Cover: Specific technologies/concepts you want to master, practical application goals, and how the company's projects/mentorship will contribute.",
    'Approach: Be specific and demonstrate how this role is a stepping stone for your long-term technical growth.'       
  ],
  'Skills Gaps': [
    'Skill: Cloud Platform Experience',
    'Severity: Medium',
    "Description: The candidate expresses interest in cloud technologies, and basic knowledge is a 'plus' for the role. However, there's no mention of hands-on experience with specific cloud providers (AWS, Azure, GCP) or services (e.g., EC2, Lambda, S3, Docker/Kubernetes deployments). For a full-stack/backend role, understanding how to deploy and manage applications in a cloud environment is valuable.",
    'Skill: Testing Frameworks & Methodologies',
    'Severity: Medium',
    "Description: While the candidate has strong project experience, there's no explicit mention of experience with unit testing, integration testing, or end-to-end testing frameworks (e.g., Jest, Mocha, Cypress for JavaScript applications). Writing maintainable and robust code often involves a good testing strategy.",
    'Skill: Deployment & CI/CD Pipelines',
    'Severity: Medium',
    "Description: The resume focuses on development and Appwrite (which abstracts much of deployment). There's no explicit mention of experience with continuous integration/continuous deployment (CI/CD) pipelines or understanding how applications are deployed to production environments beyond local development.",
    'Skill: Advanced JavaScript & Node.js Concepts (beyond immediate use)',
    'Severity: Low',
    "Description: The candidate uses React and Node.js, indicating familiarity. However, a deeper understanding of less common but critical concepts like the Node.js event loop's nuances, advanced error handling patterns, memory management, or specific performance optimizations might not be as strong as core development skills. This is a common gap for students and is expected to be learned on the job."
  ],
 'preparationPlan' : [
  {
    day: 1,
    focused_topic: "Data Structures and Algorithms & Problem Solving",
    task: [
      "Revise fundamental data structures (Arrays, Linked Lists, Trees, Hash Maps)",
      "Solve 2–3 medium-level LeetCode problems",
      "Focus on problem-solving approach and complexity analysis",
      "Review recursion and dynamic programming basics"
    ]
  },
  {
    day: 2,
    focused_topic: "JavaScript & Node.js Fundamentals",
    task: [
      "Study hoisting, closures, this keyword, and event loop",
      "Practice async/await and Promises",
      "Write small Node.js scripts using core modules (fs, http, path)",
      "Understand npm and package.json",
      "Learn how modules work in Node.js"
    ]
  },
  {
    day: 3,
    focused_topic: "Express.js, MongoDB & REST API Design",
    task: [
      "Build a mini Express API with routing and middleware",
      "Practice MongoDB CRUD operations and indexing",
      "Understand aggregation basics",
      "Design RESTful API endpoints for a sample project"
    ]
  },
  {
    day: 4,
    focused_topic: "Projects Deep Dive, Git & Cloud Fundamentals",
    task: [
      "Prepare detailed explanation of Raksha and Gym Website projects",
      "Explain architecture, challenges, and solutions",
      "Review Git advanced commands (rebase, cherry-pick, merge conflicts)",
      "Learn cloud basics: IaaS, PaaS, SaaS, serverless",
      "Explore AWS basics (EC2, S3, Lambda)"
    ]
  },
  {
    day: 5,
    focused_topic: "Behavioral Questions & Communication Practice",
    task: [
      "Practice behavioral questions using STAR method",
      "Rehearse answers about teamwork, leadership, and problem-solving",
      "Prepare 3–5 questions for interviewer",
      "Work on confidence and clear communication"
    ]
  }
];
}
