import express from 'express';
import authMiddleware from '../middlewares/auth.middleware.js';
import interviewController from '../controllers/interview.controller.js';
import upload from '../middlewares/file.middleware.js';


const router = express.Router();

/**
 * @route POST /api/interview
 * @description generate the interview report and questions for the candidate on the basis of self description , job desctription and resume
 * @access private
 */

router.post('/',authMiddleware.authUser, upload.single('resume'),interviewController.generateInterviewReportController);

/**
 * @route GET /api/interview/report/:interviewId
 * @description get interview report on the basis of interviewId
 * @access private
 */

router.get('/report/:interviewId',authMiddleware.authUser,interviewController.getInterviewByIdController);

/**
 * @route GET /api/interview/
 * @description get all the reports generated by logined user 
 * @access private
 */
router.get('/',authMiddleware.authUser,interviewController.getAllInterviewReportByUserId);
router.delete('/:interviewId', authMiddleware.authUser, interviewController.deleteInterviewReportController);

/**
 * @route POST /api/interview/:interviewId/answer
 * @description submit a single question answer for evaluation
 * @access private
 */
router.post('/:interviewId/answer', authMiddleware.authUser, upload.single('audio'), interviewController.submitAnswerController);

/**
 * @route POST /api/interview/:interviewId/complete
 * @description mark the interview as completed
 * @access private
 */
router.post('/:interviewId/complete', authMiddleware.authUser, interviewController.completeInterviewController);



export default router;